project:
  type: website
  output-dir: _site
  resources:
    - Logos/
    - styles.css

website:
  title: "North American Bat Monitoring Program in Alberta"
  site-url: https://bp-sensr.github.io/NABat-AB/